### ISSUE TITLE
Plug

### ISSUE THREAD

**Issue by Hamtar0** [piznel/gladys-xiaomi#6]
Pas de maj de status en passant la prise on via l'app Mi Home.
Pas de maj également des autres paramètres (conso)

**Comment by Hamtar0** [comment]
Faudrait en profiter pour intégrer inuse

**Comment by Hamtar0** [comment]
`warn: gladys.utils.sqlUnique was not able to find element
warn: Query = "
    SELECT dt.*
    FROM devicetype dt
    JOIN device d ON (d.id = dt.device)
    WHERE d.identifier = ?
    AND d.service = ?
    AND dt.identifier = ?;
  "
warn: Params = "["158d0001bc2bd5","xiaomi","plug"]"
warn: gladys.utils.sqlUnique was not able to find element
warn: Query = "
    SELECT dt.*
    FROM devicetype dt
    JOIN device d ON (d.id = dt.device)
    WHERE d.identifier = ?
    AND d.service = ?
    AND dt.identifier = ?;
  "
warn: Params = "["158d0001bc2bd5","xiaomi","totalpower"]"`

**Comment by piznel** [comment]
Ca sert à quoi inuse ?

**Comment by Hamtar0** [comment]
Le plug peut être allumé : ON mais pas en état de consommation par un appareil : insuse

**Comment by Hamtar0** [comment]
Info sur le totalpower ok
Pas de retour de status et inuse
`_onMessage.msg : { cmd: 'report',
  model: 'plug',
  sid: '158d0001bc2bd5',
  short_id: 25982,
  data: '{"status":"on"}' }
(node:23445) Warning: a promise was created in a handler at /Users/dguillot/Documents/GitHub/gladys/api/hooks/gladys-xiaomi/lib/xiaomi.js:100:22 but was not returned from it, see http://goo.gl/rRqMUw
    at Object.ret [as sql] (eval at makeNodePromisifiedEval (/Users/dguillot/Documents/GitHub/gladys/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
warn: gladys.utils.sqlUnique was not able to find element
warn: Query = "
    SELECT dt.*
    FROM devicetype dt
    JOIN device d ON (d.id = dt.device)
    WHERE d.identifier = ?
    AND d.service = ?
    AND dt.identifier = ?;
  "
warn: Params = "["158d0001bc2bd5","xiaomi","plug"]"
Unhandled rejection Error: Error: NotFound
    at gladys.deviceType.getByIdentifier.then.catch (/Users/dguillot/Documents/GitHub/gladys/api/hooks/gladys-xiaomi/lib/createDeviceState.js:123:43)
From previous event:
    at createDeviceState (/Users/dguillot/Documents/GitHub/gladys/api/hooks/gladys-xiaomi/lib/createDeviceState.js:122:23)
    at createDevice.then (/Users/dguillot/Documents/GitHub/gladys/api/hooks/gladys-xiaomi/lib/listen.js:40:13)
From previous event:
    at Xiaomi.shared.xiaomi.on (/Users/dguillot/Documents/GitHub/gladys/api/hooks/gladys-xiaomi/lib/listen.js:39:10)
    at emitOne (events.js:116:13)
    at Xiaomi.emit (events.js:211:7)
    at device.deviceMessage.then (/Users/dguillot/Documents/GitHub/gladys/api/hooks/gladys-xiaomi/lib/xiaomi.js:100:22)
From previous event:
    at _findDeviceMessage.then (/Users/dguillot/Documents/GitHub/gladys/api/hooks/gladys-xiaomi/lib/xiaomi.js:97:12)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Xiaomi._onMessage (/Users/dguillot/Documents/GitHub/gladys/api/hooks/gladys-xiaomi/lib/xiaomi.js:95:8)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8)
`
