### ISSUE TITLE
Gateway

### ISSUE THREAD

**Issue by Hamtar0** [piznel/gladys-xiaomi#8]
Aucun contrôle sur la gateway
``
error: Sending 500 ("Server Error") response: 
 Error: xiaomi does not exist or does not have an exec function
    at /Users/dguillot/Documents/GitHub/gladys/api/core/devicetype/deviceType.exec.js:56:31
    at /Users/dguillot/Documents/GitHub/gladys/node_modules/sails-mysql/lib/connections/spawn.js:120:16
    at Object.poolfully [as releaseConnection] (/Users/dguillot/Documents/GitHub/gladys/node_modules/sails-mysql/lib/connections/release.js:28:12)
    at Query._callback (/Users/dguillot/Documents/GitHub/gladys/node_modules/sails-mysql/lib/connections/spawn.js:105:35)
    at Query.Sequence.end (/Users/dguillot/Documents/GitHub/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/Users/dguillot/Documents/GitHub/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/Users/dguillot/Documents/GitHub/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
    at Protocol._parsePacket (/Users/dguillot/Documents/GitHub/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/dguillot/Documents/GitHub/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/Users/dguillot/Documents/GitHub/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/dguillot/Documents/GitHub/gladys/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
From previous event:
    at Object.exec (/Users/dguillot/Documents/GitHub/gladys/api/core/devicetype/deviceType.exec.js:18:6)
    at Object.exec (/Users/dguillot/Documents/GitHub/gladys/api/controllers/DeviceTypeController.js:82:8)
    at wrapper (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/lodash/lib/index.js:3275:19)
    at routeTargetFnWrapper (/Users/dguillot/Documents/GitHub/gladys/node_modules/sails/lib/router/bind.js:181:5)
    at callbacks (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/express/lib/router/index.js:164:37)
    at param (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/express/lib/router/index.js:138:11)
    at param (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/express/lib/router/index.js:135:11)
    at pass (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/express/lib/router/index.js:145:5)
    at nextRoute (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/express/lib/router/index.js:100:7)
    at callbacks (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/express/lib/router/index.js:167:11)
    at module.exports (/Users/dguillot/Documents/GitHub/gladys/api/policies/checkToken.js:4:12)
    at routeTargetFnWrapper (/Users/dguillot/Documents/GitHub/gladys/node_modules/sails/lib/router/bind.js:181:5)
    at callbacks (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/express/lib/router/index.js:164:37)
    at param (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/express/lib/router/index.js:138:11)
    at param (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/express/lib/router/index.js:135:11)
    at pass (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/express/lib/router/index.js:145:5)
    at nextRoute (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/express/lib/router/index.js:100:7)
    at callbacks (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/express/lib/router/index.js:167:11)
    at _sendHeaders (/Users/dguillot/Documents/GitHub/gladys/node_modules/sails/lib/hooks/cors/to-prepare-send-headers.js:91:7)
    at routeTargetFnWrapper (/Users/dguillot/Documents/GitHub/gladys/node_modules/sails/lib/router/bind.js:181:5)
    at callbacks (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/express/lib/router/index.js:164:37)
    at param (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/express/lib/router/index.js:138:11)
    at pass (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/express/lib/router/index.js:145:5)
    at nextRoute (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/express/lib/router/index.js:100:7)
    at callbacks (/Users/dguillot/Documents/GitHub/gladys/node_modules/@sailshq/express/lib/router/index.js:167:11)
``

**Comment by piznel** [comment]
Pb de mot de passe ou ce n'est pas la bonne gateway. Tu as essayé les 2 ?
